name: Performance test
on: workflow_dispatch
jobs:
    build:
        name: Performance Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.0]
                node-version: [16.x]
        steps:
            - name: Checkout gutenberg
              run: | 
                  git clone https://github.com/WordPress/gutenberg.git
                  rm -rf gutenberg/.git
                  cd gutenberg
                  ls -lia

            - name: Using Node version ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Installing wordpress environment
              run: npm install -g @wordpress/env

            - name: npm install, build
              run: |
                  ls -la
                  npm install
                  npm run build

            - name: run performance test
              run: |
                  npm run test-performance packages/e2e-tests/specs/performance/post-editor.test.js

