name: Performance test
on: push
jobs:
    build:
        name: Performance Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.0]
                node-version: [14.x]
        steps:
            - name: clone repositories
              run: |
                git clone https://github.com/WordPress/gutenberg.git
                git clone https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/CakeWP/block-options.git

            - name: switch to a stable gutenberg branch
              working-directory: ./gutenberg
              run: |
                git checkout tags/v11.8.0 -b 'stable-tag'
            
            - name: install wp cli
              run: |
                curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && sudo mv wp-cli.phar /usr/local/bin/wp

            - name: get current branch name
              id: branch-name
              env:
                ACTIONS_ALLOW_UNSECURE_COMMANDS: true
              uses: tj-actions/branch-names@v5

            - name: using Node version ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: npm install, build
              working-directory: ./gutenberg 
              run: |
                  ls -la
                  npm ci
                  npm run build

            - name: starting the wp enviroment
              working-directory: ./gutenberg
              run: |
                npm run wp-env start

            - name: run performance test without editorskit
              working-directory: ./gutenberg
              run: |
                npm run test-performance packages/e2e-tests/specs/performance/post-editor.test.js

            - name: stop the wp environment
              working-directory: ./gutenberg
              run:
                npm run wp-env stop

            - name: setup, install and build editorskit
              working-directory: ./block-options
              env:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              run: |
                git checkout ${BRANCH_NAME}

                npm ci
                npm run build

            - name: include editorskit in the environment config
              working-directory: ./gutenberg
              run: |
                ls -la
                sed -I -e 's/"\."/".", "..\/block-options"/g' .wp-env.json
                cat .wp-env.json

            - name: start wordpress environment
              working-directory: ./gutenberg
              run: |
                npm run wp-env start --update

            - name: run performance test with editorskit
              working-directory: ./gutenberg
              run: |
                npm run test-performance packages/e2e-tests/specs/performance/post-editor.test.js